### ISSUE TITLE
Instructor Feedback - Week 5

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [haandahl/income-experiences#2]
Nice job here @haandahl. I think you'll be really happy down the road that you have this done in your indie project already! 

- [x] re: your Todo about treeset versus hashset here: https://github.com/haandahl/income-experiences/blob/ae5304702b9c5813ee88770d5fb4523c2580889f/src/main/java/com/heidiaandahl/entity/User.java#L33. I think the decision here is around whether you want these sorted when they come back. If you do, then you will need to implement the comparable interface in Story and decided what kind of ordering you want (by date, name, etc.).  
- [x] It's probably time to implement the generic dao.
- [x] You may want to be careful with the toString on entities that have relationships.  If User.toString writes out the Stories, and Story.toString writes out the User, you could end up with an out of my memory error if you called toString (sort of an endless loop).  You might test this by writing out a user that has stories...

**Comment by haandahl** [comment]
Thanks for checking out my TODO's!  The first is not implemented yet, but I added your feedback to the TODO in my code so that I can consider it when I am ready to use it.
