### ISSUE TITLE
Design Review Feedback from Ellis

### ISSUE THREAD

**Issue by smnkdrnk** [haandahl/income-experiences#3]
# Design/Code Review 1

### Reviewer: Ellison Wagner

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br>2. Is professional and free of typos, slang, etc.<br>3. Fully explains the problem and the solution<br>4. Is understandable by the average person|Problem statement is thorough and very clear about what you are trying to achieve.<br>There's one or two small typos/errors ("an narrative") but overall well presented.<br>In the event not all features are implemented (eg the stretch goals), you could updated the problem statement to reflect the final level of functionality. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use.<br>2. The order in which values are displayed are logical and easy to understand/use<br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens|Well organized and easy to browse and review. Great idea putting all mock ups into one document.<br>The only concern I would have as a user is having my posts edited, which we talked about in your review. You could clarify what you mean by having an admin edit an entry.<br>Wireframes are detailed and logically laid out - I guess the next step is just to proceed to code them up. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model<br>2. There is at least one 1-to-many relationship.<br>3. The model represents good database design |Everything seems to be documented in your ERD.<br>Foreign key relationships are defined.<br>Supplementary details provided by note on ERD adds some context. |
|**Code**|1. Proper Maven project structure is used<br>2. a .gitignore file for IntelliJ Java projects has been implemented<br>3. There is not any redundant or copy/paste code in the JSPs or classes<br>4. Classes are appropriately-sized (no monster classes)Property files are used appropriately: no hard-coded values<br>5. Logging statements are used rather than System.out.println and printStackTrace.<br>6. There are appropriate unit tests/code coverages. |Logging and hibernate integrated into code so far.<br>Next step is to work on views/JSPs.<br>You may be able to find a JS library to incorporate an autocomplete functionality. I found a few examples like Awesomplete (JS and CSS), Autocomplete jQuery UI (jQuery), and algolia/autocomplete (heavier tool using jQuery, JavaScript, and Angular) |
|Overall you've made a lot of progress in your project, and I think you're in a great place with lots of forward momentum behind you. It is difficult to find two suggestions for improvement in each category, because I think you're hitting all the right benchmarks and then some.|

**Comment by haandahl** [comment]
Cool ideas about auto-complete. The way the BLS api is structured, I am instead going to pre-populate some career options to search instead of having the user type something in.

**Comment by haandahl** [comment]
Fixed typos in problem statement and removed unused scope. I did not revise the user stories to explain an admin editing content, because the stories represent original(ish) scope and my final scope does not include an admin editing user's content directly; rather the admin can change visibility status.
