### ISSUE TITLE
Design Review Feedback from Norm

### ISSUE THREAD

**Issue by Normnondo** [haandahl/income-experiences#4]
Item | Considerations | Comments/Suggestions
-- | -- | --
  |   | Reviewer comments and suggestions go here. Each item should have at least one "kudos" and two suggestions for improvement
Problem Statement | 1. Accurately describes project purpose2. Is professional and free of typos, slang, etc.3. Fully explains the problem and the solution4. Is understandable by the average person |  Good problem statement, no glaring typos, no jargon, easy to understand. Clear on what your are trying to do. 
Design Documentation | 1. Navigation/flow through the application is logical and easy to use. 2. The order in which values are displayed are logical and easy to understand/use 3. The order in which the form fields entered are logical and easy to understand/use  4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |  Things make sense in how they're laid out.  Forms to be filled out are in a good order.  Easy to navigate through and find what you're looking for.  
Data model/Database | 1. Everything on the screens and problem statement/flow is represented in the model2. There is at least one 1-to-many relationship.3. The model represents good database design. | Good ERD, one-to-many relationship established. Need to decide whether to put the two databases together that you discussed during the review.r.  
Code | 1. Proper Maven project structure is used2. a .gitignore file for IntelliJ Java projects has been implemented 3. There is not any redundant or copy/paste code in the JSPs or classes4. Classes are appropriately-sized (no monster classes)Property files are used appropriately: no hard-coded values 5. Logging statements are used rather than System.out.println and printStackTrace.6. There are appropriate unit tests/code coverages. | Hibernate is being used, some logging in effect.  Testing is being done.  Next steps would be to get things put together with your logic, allow for actual data entry.

**Comment by haandahl** [comment]
Database decisions are made and site allows data entry!
