### ISSUE TITLE
Instructor Feedback - Week 7 Auth

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [haandahl/income-experiences#5]
Looks like a great start here on auth and that you are thinking carefully about security with regard to your various user types and all related resources.

You may find that to get very fine-grained control over specific data when using a servlet that serve a couple different user types (view my profile versus view somebody else's profile), you may want to check the role within the servlet. The other option would be to set up two servlets ViewMyProfile versus ViewOtherProfile. I can think of pros and cons to each approach...

**Comment by haandahl** [comment]
Thanks - noted (not yet implemented)
